services:
  db:
    image: mysql:8.0
    container_name: scommit-db
    restart: unless-stopped
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  back:
    image: ghcr.io/prgrms-be-devcourse/nbe10-12-3-team3:latest
    container_name: scommit-app
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      CORS_ALLOWED_ORIGIN: ${CORS_ALLOWED_ORIGIN}
    depends_on:
      db:
        condition: service_healthy

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  mysql-exporter:
    image: prom/mysqld-exporter
    container_name: scommit-mysql-exporter
    restart: unless-stopped
    ports:
      - "9104:9104"
    volumes:
      - ./mysql-exporter.cnf:/tmp/my.cnf
    command: --config.my-cnf=/tmp/my.cnf
    depends_on:
      db:
        condition: service_healthy

  promtail:
    image: grafana/promtail:latest
    container_name: scommit-promtail
    user: root
    restart: unless-stopped
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

volumes:
  mysql_data:
