spring:
  datasource:
    url: jdbc:h2:file:./back/triples;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

logging:
  level:
    org.hibernate.SQL: debug

file:
  path: back/src/main/resources/static/media/

cors:
  allowed-origins: http://localhost:3000

cookie:
  domain: localhost
