spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false
logging:
  level:
    org.hibernate.SQL: debug


auth-token:
  access-token:
    secret-key: dGVzdC1zZWNyZXQta2V5LWZvci1qd3QtdW5pdC10ZXN0aW5nLW1pbmltdW0tMzJieXRlcy1yZXF1aXJlZA==
    expiration: 30m
    cookie-max-age: 30m
  refresh-token:
    cookie-max-age: 30d


file:
  path: ./build/test-uploads

cors:
  allowed-origins: http://localhost:3000

cookie:
  domain: localhost
