server:
  forward-headers-strategy: native
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  datasource:
    url: "jdbc:mysql://db:3306/${DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 1000
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGIN}

cookie:
  domain: scommit.store

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
